/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.*/

#include <bits/stdc++.h>
using namespace std;

// Time:O(N+M);
// Space:O(26)~O(1);
class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        unordered_map<char, int> m;
        for (int i = 0; i < s.length(); i++)
        {
            m[s[i]]++;
        }
        for (int j = 0; j < t.length(); j++)
        {
            if (m[t[j]] >= 1)
                m[t[j]]--;
            else
                return t[j];
        }
        return -1;
    }
};
// Time-O(N+M);
// Space-O(1);

class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        int x = 0, y = 0;
        for (int i = 0; i < s.length(); i++)
        {
            x += int(s[i]) - 97;
        }
        for (int j = 0; j < t.length(); j++)
        {
            y += int(t[j]) - 97;
        }
        return char(y - x + 97);
    }
};